## Programa Ingenias+ Data Science

## Trabajando con Pandas

1) Importa las librerias requeridas: `Pandas` y `NumPy`.  

Una buena practica a la hora de escribir codigo es de comentar siempre que estoy haciendo (usando `#`) en la linea anterior. Por mas obvio que parezca lo que voy a hacer, puede ser que tenga que compartir el documento con otras personas y no sepan que quise hacer en cada linea. O que yo mismo lea el codigo tiempo despues y no recuerde porque lo hice.

In [6]:
import numpy as np
import pandas as pd

2) Lee el archivo csv `life_expectancy_data` usando `pandas`. Guardalo en una variable llamada `expvida`.

In [7]:
# Leer el archivo CSV y guardarlo en la variable expvida
expvida = pd.read_csv('Life_Expectancy_Data.csv', delimiter=',')

In [11]:
expvida

,Country,Year,Status,life_expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

3) ¿Que tipo de estructura de datos contiene la variable `expvida`?

In [ ]:
# Obtengo el tipo de estructura de datos
type(expvida)

pandas.core.frame.DataFrame

4) ¿Cuantas filas y columnas tiene `expvida`?

In [ ]:
# Uso .shape para obtener cantidad de filas y columnas
expvida.shape
print (f"Expvida tiene {expvida.shape[0]} filas y {expvida.shape[1]} columnas}")

(2938, 22)

**Numero de filas**:

**Numero de columnas**:

5) ¿Cual es el nombre de las columnas contenidas en `expvida`?

In [ ]:
# Obtengo el nombre de las columnas
expvida.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

6) Inspecciona las primeras 10 filas de `expvida`

In [ ]:
# Inspecciono las primeras filas
expvida.head(10)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
5,Afghanistan,2010,Developing,58.8,279.0,74,0.01,79.679367,66.0,1989,...,66.0,9.20,66.0,0.1,553.328940,2883167.0,18.4,18.4,0.448,9.2
6,Afghanistan,2009,Developing,58.6,281.0,77,0.01,56.762217,63.0,2861,...,63.0,9.42,63.0,0.1,445.893298,284331.0,18.6,18.7,0.434,8.9
7,Afghanistan,2008,Developing,58.1,287.0,80,0.03,25.873925,64.0,1599,...,64.0,8.33,64.0,0.1,373.361116,2729431.0,18.8,18.9,0.433,8.7
8,Afghanistan,2007,Developing,57.5,295.0,82,0.02,10.910156,63.0,1141,...,63.0,6.73,63.0,0.1,369.835796,26616792.0,19.0,19.1,0.415,8.4
9,Afghanistan,2006,Developing,57.3,295.0,84,0.03,17.171518,64.0,1990,...,58.0,7.43,58.0,0.1,272.563770,2589345.0,19.2,19.3,0.405,8.1

7) Y ahora las 10 ultimas.

In [ ]:
# Inspecciono las ultimas filas
expvida.tail(10)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
2928,Zimbabwe,2009,Developing,50.0,587.0,30,4.64,1.040021,73.0,853,...,69.0,6.26,73.0,18.1,65.824121,1381599.0,7.5,7.4,0.419,9.9
2929,Zimbabwe,2008,Developing,48.2,632.0,30,3.56,20.843429,75.0,0,...,75.0,4.96,75.0,20.5,325.678573,13558469.0,7.8,7.8,0.421,9.7
2930,Zimbabwe,2007,Developing,46.6,67.0,29,3.88,29.814566,72.0,242,...,73.0,4.47,73.0,23.7,396.998217,1332999.0,8.2,8.2,0.414,9.6
2931,Zimbabwe,2006,Developing,45.4,7.0,28,4.57,34.262169,68.0,212,...,71.0,5.12,7.0,26.8,414.796232,13124267.0,8.6,8.6,0.408,9.5
2932,Zimbabwe,2005,Developing,44.6,717.0,28,4.14,8.717409,65.0,420,...,69.0,6.44,68.0,30.3,444.765750,129432.0,9.0,9.0,0.406,9.3
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

8) ¿Que tipos de datos contiene cada una de las columnas de `expvida`?

In [ ]:
# Tipo de datos en cada columna
expvida.dtypes

Country                             object
Year                                 int64
Status                              object
Life expectancy                    float64
Adult Mortality                    float64
infant deaths                        int64
Alcohol                            float64
percentage expenditure             float64
Hepatitis B                        float64
Measles                              int64
 BMI                               float64
under-five deaths                    int64
Polio                              float64
Total expenditure                  float64
Diphtheria                         float64
 HIV/AIDS                          float64
GDP                                float64
Population                         float64
 thinness  1-19 years              float64
 thinness 5-9 years                float64
Income composition of resources    float64
Schooling                          float64
dtype: object

9) ¿Hay valores faltantes en alguna de las columnas de `expvida`?

In [ ]:
# Obtengo la cantidad de datos faltantes en cada columna
expvida.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

10) Selecciona el maximo de datos faltantes. Calcula que porcentaje de los datos representan los datos faltantes.

In [ ]:
# Obtengo el maximo valor de datos faltantes y lo guardo en la variable masnan
masnan=expvida.isnull().sum().max()

In [ ]:
masnan

652

In [ ]:
# Obtengo la cantidad de filas total y divido el maximo valor de datos faltantes por este numero
# y lo multiplico por 100
total_filas=expvida.shape[0]
porcentaje=(masnan/total_filas)*100

In [ ]:
# Imprimo el maximo porcentaje de datos faltantes. Uso f-strings.
print(f"El porcentaje de datos faltantes es: {porcentaje:.2f}%")

###.2f redondea a 2 decimales

El porcentaje de datos faltantes es: 22.19%

In [ ]:
por_srt = str(porcentaje)
type(por_str)

print(type(por_str))

- str.format()
- Template Class
- f-strings

#### Ahora vamos a realizar algunos calculos y manipulaciones sobre las columnas.

Una función útil para este fin es: `.rename()`. Y podemos utilizarla de la siguiente manera: Si `df` es mi DataFrame y quiero renombrar la columna `columna` como `columna1`, y la columna `columna2` como `columna3`, utilizo la siguiente sintaxis:
  
`df.rename(columns={"columna": "columna1", "columna2": "columna3"}, inplace=True)`

11) Renombra la columna 'Life expectancy ' como 'life_expectancy', ' BMI ' como 'bmi' y ''Measles ' como 'measles'. No olvides de usar `inplace` para modificar el DataFrame original. Luego chequea que el cambio se haya hecho correctamente.

In [9]:
# Renombro columnas del DataFrame
expvida.rename(columns={"Life expectancy ": "life_expectancy", "Measles ": "measles", " BMI ": "bmi"}, inplace=True)

###inplace=true modifica el dataframe original

In [ ]:
# Chequeo que se hayan reemplazado correctamente
expvida.columns

Index(['Country', 'Year', 'Status', 'life_expectancy', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'measles', 'bmi', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

12) ¿Cual es el promedio de expectativa de vida (Life expectancy) en general?

In [15]:
# Obtengo el promedio de la columna
promedio_general = expvida['life_expectancy'].median()
print(f"El promedio de expectativa de vida es: {promedio_general:.2f}")

###expvida['life_expectancy'].median().round(2) redondear 2 decimas con round
###promedio_general = expvida['life_expectancy'].median().round(2)
### promedio_redondeado = promedio_redondeado = round(promedio, 2)
###print(promedio_redondeado)

El promedio de expectativa de vida es: 72.10

13) ¿Cual es el promedio de expectativa de vida (Life expectancy) por país?

In [ ]:
# Obtengo el promedio por pais
promedio_por_pais = expvida.groupby('Country')['life_expectancy'].mean()
#Ordenar de forma ascendente los países por su promedio de expectativa de vida
promedio_por_pais.sort_values(ascending=False)

###ver como redondear en 2 cifraas

Country
Japan                    82.53750
Sweden                   82.51875
Iceland                  82.44375
Switzerland              82.33125
France                   82.21875
                           ...
Niue                          NaN
Palau                         NaN
Saint Kitts and Nevis         NaN
San Marino                    NaN
Tuvalu                        NaN
Name: life_expectancy, Length: 193, dtype: float64

14) ¿Cual es la expectativa de vida mas alta y mas baja? Usa la funcion de pandas y la funcion de NumPy y compara el resultado. ¿Que paises tienen esas expectativas de vida?

In [ ]:
# Maxima expectativa de vida usando numpy

## Convertir la columna a un array de NumPy
valores_vida = expvida['life_expectancy'].values

## Calcular el máximo ignorando NaN, sino da NaN
expvida_max_numpy = np.nanmax(valores_vida)

print(f"Máxima expectativa de vida (NumPy): {expvida_max_numpy} años")

Máxima expectativa de vida (NumPy): 89.0

In [ ]:
# Maxima expectativa de vida usando pandas
expvida_max_pandas = expvida['life_expectancy'].max()
print(f"Máxima expectativa de vida (Pandas): {expvida_max_pandas} años")

Máxima expectativa de vida (PAndas): 89.0años

In [ ]:
# Minima expectativa de vida usando numpy

## Convertir la columna a un array de NumPy
valores_vida = expvida['life_expectancy'].values

## Calcular el mínimo ignorando NaN, sino da NAN
expvida_min_numpy = np.nanmin(valores_vida)

print(f"Mínima expectativa de vida (NumPy): {expvida_min_numpy} años")

Mínima expectativa de vida (NumPy): 36.3

In [ ]:
# Minima expectativa de vida usando pandas
expvida_min_pandas = expvida['life_expectancy'].min()
print(f"Mínima expectativa de vida (Pandas): {expvida_min_pandas} años")

Mínima expectativa de vida (Pandas): 36.3años

In [ ]:
# Muestro los resultados maximos
print(f"La expectativa de vida mas alta es de {expvida_max_pandas} años")

La expectativa de vida mas alta es de 89.0 años

In [ ]:
# Muestro los resultados minimos
print(f"La expectativa de vida mas baja es de {expvida_min_pandas} años")

La expectativa de vida mas baja es de 36.3 años

In [ ]:
# Filtro las columnas para mostrar solo las filas que tengan valor
# igual al maximo
expvida_filas_max = expvida[expvida['life_expectancy'] == expvida_max_pandas]
print("Paises con la expectativa de vida mas alta:")
print(expvida_filas_max[['Country', 'life_expectancy']])

Paises con la expectativa de vida mas alta:
          Country  life_expectancy
241       Belgium             89.0
915       Finland             89.0
937        France             89.0
938        France             89.0
995       Germany             89.0
1293        Italy             89.0
1850  New Zealand             89.0
1916       Norway             89.0
2056     Portugal             89.0
2433        Spain             89.0
2513       Sweden             89.0

In [ ]:
# Filtro las columnas para mostrar solo las filas que tengan valor
# igual al minimo
expvida_filas_min = expvida[expvida['life_expectancy'] == expvida_min_pandas]
print("Paises con la expectativa de vida mas baja:")
print(expvida_filas_min[['Country', 'life_expectancy']])

Paises con la expectativa de vida mas baja:
     Country  life_expectancy
1127   Haiti             36.3

15) ¿Cuantas categorias encontramos en la columna "Status"? _**Pista**_: Lee acerca de la función [unique()](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.unique.html?highlight=unique#pandas.Series.unique)

In [ ]:
# Obtengo los valores unicos de la columna status
categorias_status = expvida['Status'].unique()
print("Categorías en 'Status':", categorias_status)

Categorías únicas en 'Status': ['Developing' 'Developed']

16) ¿Cuantos paises se ubican en cada una de esas categorias de "Status"? _**Pista**_: Lee acerca de la función [value_counts()](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html)

In [ ]:
# Cuento cuantos valores hay de cada categoria
expvida['Status'].value_counts()

Status
Developing    2426
Developed      512
Name: count, dtype: int64

18) ¿Cuantos paises presentaron algun caso de Sarampion (**Measles**) en el 2015? **_Pista_**: Lee acerca de la función [.count()](http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.count.html?highlight=count#pandas.DataFrame.count)

In [ ]:
# Cuento cuantas filas tienen valores distintos de cero

##Filtrar datos del 2015
casos_2015 = expvida[expvida['Year'] == 2015]
##Casos con sarampion >0
casos_sarampion = casos_2015[casos_2015['measles'] > 0]
##Cantidad de paises con sarampion en 2025
cantidad_paises = casos_sarampion['Country'].nunique()

print(f"En 2015, {cantidad_paises} países presentaron al menos un caso de sarampión.")

En 2015, 121 países presentaron al menos un caso de sarampión.